### ISSUE TITLE
log function requires an integer

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim-Data-Analyser#5]
When tippecanoe returns an error, then an exception is thrown while the error is being printed:

```
tippecanoe: must specify -o out.mbtiles or -e directory
Traceback (most recent call last):
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipes/output_formatters/vector_tile_formatter.py", line 42, in call_tippecanoe
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tippecanoe', '--output-to-directory=/srv/qa-data.nominatim.org/qa-data/addr_housenumber_no_digit/vector-tiles', '--force', '--no-tile-compression', '--no-tile-size-limit', '--no-feature-limit', '--buffer=120', '--no-clipping', '-r1', '--cluster-distance=60']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 17, in <module>
    Core().execute_all()
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/core.py", line 28, in execute_all
    self.execute_one(file_without_ext)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/core.py", line 36, in execute_one
    PipelineAssembler(loaded_yaml, name).assemble().process_and_next()
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipe.py", line 38, in process_and_next
    result = pipe.process_and_next(result)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipe.py", line 38, in process_and_next
    result = pipe.process_and_next(result)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipe.py", line 38, in process_and_next
    result = pipe.process_and_next(result)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipe.py", line 36, in process_and_next
    result = self.process(data)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipes/output_formatters/vector_tile_formatter.py", line 28, in process
    self.call_tippecanoe(self.base_folder_path, feature_collection)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipes/output_formatters/vector_tile_formatter.py", line 61, in call_tippecanoe
    self.log(logging.FATAL, e)
  File "/srv/qa-data.nominatim.org/Nominatim-Data-Analyser/analyser/core/pipe.py", line 84, in log
    LOG.log(level, f'Rule <{self.exec_context.rule_name}> : {msg}')
  File "/usr/lib/python3.8/logging/__init__.py", line 1508, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
Command exited with non-zero status 1
```

This looks like a bug in the `log()` function in pipe.py.

**Comment by AntoJvlt** [comment]
Thanks, indeed the log function was called with the wrong parameters order when an exception was raised by the call to tippecanoe.

I just fixed this.
